language: python
cache: pip
dist: bionic

arch:
  - arm64
  - amd64
  - ppc64le

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

install: pip install -U -e .[test,docs]

script:
  - python -m unittest discover -v greenlet.tests
  - sphinx-build -b doctest -d docs/_build/doctrees2 docs docs/_build/doctest2
