language: python
cache: pip

matrix:
  include:
  - arch: arm64
    python: 2.7
    dist: bionic
  - arch: amd64
    python: 2.7
    dist: bionic
  - arch: ppc64le
    python: 2.7
    dist: bionic
  - arch: arm64
    python: 3.5
    dist: bionic
  - arch: amd64
    python: 3.5
    dist: bionic
  - arch: ppc64le
    python: 3.5
    dist: bionic
  - arch: arm64
    python: 3.6
    dist: bionic
  - arch: amd64
    python: 3.6
    dist: bionic
  - arch: ppc64le
    python: 3.6
    dist: bionic
  - arch: arm64
    python: 3.7
    dist: bionic
  - arch: amd64
    python: 3.7
    dist: bionic
  - arch: ppc64le
    python: 3.7
    dist: bionic
  - arch: arm64
    python: 3.8
    dist: bionic
  - arch: amd64
    python: 3.8
    dist: bionic
  - arch: ppc64le
    python: 3.8
    dist: bionic
  - arch: arm64
    python: 3.9
    dist: bionic
  - arch: amd64
    python: 3.9
    dist: bionic
  - arch: ppc64le
    python: 3.9
    dist: bionic

install: pip install -U -e .[test]

script: python run-tests.py
